name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: nodejs gnome-shell-extensions

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
